version: '3'
services:
    tracker:
        build: .
        restart: always
        ports:
            - 3000:3000
        environment:
            - ACKEE_MONGODB=mongodb://mongo:27017/ackee
        env_file:
            - .env
        depends_on:
            - mongo
    mongo:
        image: mongo:4.4.0
        restart: always
        volumes:
            - ./data:/data/db
